---
- name: Update packages for Alpine
  become: true
  community.general.apk:
    update_cache: true
    upgrade: true
  when: ansible_pkg_mgr == "apk"

- name: Update packages for Arch
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_pkg_mgr == "pacman"

- name: Update packages for Debian
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    upgrade: full
  become: true
  when: ansible_pkg_mgr == "apt"

- name: Update packages for Fedora
  ansible.builtin.dnf:
    # Don't use 'name: "*"' here. It will throw an error, since updating all
    # packages will replace dnf.
    autoremove: true
    update_cache: true
  become: true
  when: ansible_pkg_mgr in ["dnf", "dnf5"]

- name: Update packages for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: ansible_system == "Darwin"
