---
python_uv_arch_:
  amd64: x86_64
  arm64: aarch64
python_applications:
  - "jinja2-cli[toml,yaml,xml]"
  - "black[jupyter]"
  - cookiecutter
  - jupytext
  - name: poetry
    extras:
      - poetry-plugin-shell
      - poetry-plugin-up
  - pyright
  - ruff
python_uv_arch: "{{ python_uv_arch_[system_architecture] }}"
