---
- name: Install utilities for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - htop
      - rsync
  when: ansible_system == "FreeBSD"

- name: Install utilities for Linux
  ansible.builtin.package:
    name:
      - htop
      - rsync
  become: true
  when: ansible_system == "Linux"

- name: Install utilities for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name:
      - htop
      - rsync
  when: ansible_system == "Darwin"
