---
- name: Install Zoxide for FreeBSD
  become: true
  community.general.pkgng:
    name: zoxide
  when: ansible_system == "FreeBSD"

# TODO: Renable when Zoxide package in most distributions reaches version 0.9.4.
# - name: Install Zoxide for Linux
#   ansible.builtin.package:
#     name: zoxide
#   become: true
#   ignore_errors: true
#   register: zoxide_linux
#   when: ansible_system == "Linux"

- name: Get latest Zoxide version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/zoxide.json
  register: zoxide_formula
  when: ansible_system == "Linux"

- name: Download Zoxide for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/ajeetdsouza/zoxide/releases/download/v{{
      zoxide_formula.json.versions.stable }}/zoxide-{{
      zoxide_formula.json.versions.stable }}-{{ zoxide_arch[system_architecture]
      }}-unknown-linux-musl.tar.gz
  vars:
    zoxide_arch:
      amd64: x86_64
      arm64: aarch64
  when: ansible_system == "Linux"

- name: Install Zoxide for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/zoxide
    force: true
    mode: "755"
    remote_src: true
    src: /tmp/zoxide
  become: true
  when: ansible_system == "Linux"

- name: Install Zoxide for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: zoxide
  when: ansible_system == "Darwin"

- name: Install Zoxide for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: zoxide
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Linux
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system == "Linux"

- name: Install Zoxide shell completions for Linux
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: /tmp/completions/zoxide.{{ item.shell }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/zoxide"
      shell: bash
    - dest: "{{ fish_completion }}/zoxide.fish"
      shell: fish
  when: ansible_system == "Linux"

- name: Create Nushell autoload directories for Unix
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    path: "{{ nushell_user_autoload }}"
    state: directory
  become: true
  when: ansible_system != "Win32NT"

- name: Generate Zoxide Nushell configuration for Unix
  ansible.builtin.shell: >-
    zoxide init --cmd cd nushell > {{ nushell_user_autoload }}/zoxide.nu
  become: true
  changed_when: true
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: ansible_system != "Win32NT"

- name: Create Nushell autoload directories for Windows
  ansible.windows.win_file:
    owner: "{{ user_id }}"
    path: "{{ nushell_user_autoload }}"
    state: directory
  when: ansible_system == "Win32NT"

- name: Generate Zoxide Nushell configuration for Windows
  # Using "WriteAllLines" to avoid the Byte Order Mark (BOM) that PowerShell 5
  # prepends to outputs redirected to files.
  ansible.windows.win_shell: |
    $Text = zoxide init --cmd cd nushell
    [System.IO.File]::WriteAllLines("{{ nushell_user_autoload }}/zoxide.nu", $Text)
  changed_when: true
  environment:
    Path: "{{ scoop_apps }}\\zoxide\\current;{{ ansible_env.Path }}"
  when: ansible_system == "Win32NT"
