# Helix configuration file for text editing.
#
# For more information, visit https://docs.helix-editor.com/configuration.html.

theme = "solarized_light"

[editor]
auto-completion = false
auto-pairs = false
bufferline = "multiple"
color-modes = true
cursorline = true
true-color = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = true

[editor.statusline]
right = [
    "version-control",
    "diagnostics",
    "selections",
    "register",
    "position",
    "file-line-ending",
    "file-encoding",
]

[keys.insert]
"\ue000" = "move_char_right"
"\ue001" = "jump_backward"
"\ue002" = "jump_forward"
"\ue003" = "completion"
A-b = "move_prev_word_start"
A-d = "delete_word_forward"
A-f = "move_next_word_end"
C-a = "goto_line_start"
C-d = "delete_word_backward"
C-e = "goto_line_end_newline"
C-i = "no_op"
C-j = "move_char_left"
C-k = "move_line_down"
C-l = "move_line_up"
C-o = "no_op"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
S-left = "move_prev_long_word_start"
S-right = "move_next_long_word_end"

[keys.normal]
";" = "move_char_right"
"\ue000" = "move_char_right"
"\ue001" = "jump_backward"
"\ue002" = "jump_forward"
A-b = "move_prev_word_start"
A-d = "delete_word_forward"
A-f = "move_next_word_end"
c = "change_selection_noyank"
C-a = "goto_line_start"
C-d = "delete_word_backward"
C-e = "goto_line_end_newline"
C-i = "no_op"
C-j = "move_char_left"
C-k = "move_line_down"
C-l = "move_line_up"
C-o = "no_op"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
D = "delete_char_backward"
d = "delete_selection_noyank"
esc = ["collapse_selection", "keep_primary_selection"]
h = "no_op"
j = "move_char_left"
k = "move_line_down"
l = "move_line_up"
S-left = "move_prev_long_word_start"
S-right = "move_next_long_word_end"
X = ["extend_to_line_bounds", "trim_selections"]

[keys.normal.C-w]
";" = "jump_view_right"
":" = "swap_view_right"
C-h = "no_op"
C-i = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"
C-o = "no_op"
C-q = "no_op"
C-s = "no_op"
C-t = "no_op"
C-v = "no_op"
C-w = "no_op"
down = "no_op"
h = "no_op"
H = "no_op"
j = "jump_view_left"
J = "swap_view_left"
k = "jump_view_down"
K = "swap_view_down"
l = "jump_view_up"
L = "swap_view_up"
left = "no_op"
right = "no_op"
up = "no_op"

[keys.normal.g]
";" = "goto_line_end_newline"
h = "no_op"
j = "goto_line_start"
k = "goto_previous_buffer"
l = "goto_next_buffer"
n = "no_op"
p = "no_op"

[keys.normal.space]
A-c = "no_op"

[keys.normal.space.w]
";" = "jump_view_right"
":" = "swap_view_right"
C-h = "no_op"
C-i = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"
C-o = "no_op"
C-q = "no_op"
C-s = "no_op"
C-t = "no_op"
C-v = "no_op"
C-w = "no_op"
down = "no_op"
h = "no_op"
H = "no_op"
j = "jump_view_left"
J = "swap_view_left"
k = "jump_view_down"
K = "swap_view_down"
l = "jump_view_up"
L = "swap_view_up"
left = "no_op"
right = "no_op"
up = "no_op"

[keys.normal.z]
backspace = "no_op"
down = "no_op"
pagedown = "no_op"
pageup = "no_op"
space = "no_op"
up = "no_op"
z = "no_op"

[keys.normal.Z]
backspace = "no_op"
down = "no_op"
pagedown = "no_op"
pageup = "no_op"
space = "no_op"
up = "no_op"
z = "no_op"

[keys.select]
";" = "extend_char_right"
"\ue001" = "jump_backward"
"\ue002" = "jump_forward"
c = "change_selection_noyank"
A-b = "extend_prev_word_start"
A-f = "extend_next_word_end"
C-a = "goto_line_start"
C-e = "goto_line_end_newline"
C-i = "no_op"
C-o = "no_op"
C-left = "extend_prev_word_start"
C-right = "extend_next_word_end"
esc = "normal_mode"
h = "no_op"
j = "extend_char_left"
k = "extend_line_down"
l = "extend_line_up"
S-left = "extend_prev_long_word_start"
S-right = "extend_next_long_word_end"
X = ["extend_to_line_bounds", "trim_selections"]

[keys.select.C-w]
";" = "jump_view_right"
":" = "swap_view_right"
C-h = "no_op"
C-i = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"
C-o = "no_op"
C-q = "no_op"
C-s = "no_op"
C-t = "no_op"
C-v = "no_op"
C-w = "no_op"
down = "no_op"
h = "no_op"
H = "no_op"
j = "jump_view_left"
J = "swap_view_left"
k = "jump_view_down"
K = "swap_view_down"
l = "jump_view_up"
L = "swap_view_up"
left = "no_op"
right = "no_op"
up = "no_op"

[keys.select.g]
";" = "goto_line_end_newline"
h = "no_op"
j = "goto_line_start"
k = "goto_previous_buffer"
l = "goto_next_buffer"
n = "no_op"
p = "no_op"

[keys.select.space]
A-c = "no_op"

[keys.select.space.w]
";" = "jump_view_right"
":" = "swap_view_right"
C-h = "no_op"
C-i = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"
C-o = "no_op"
C-q = "no_op"
C-s = "no_op"
C-t = "no_op"
C-v = "no_op"
C-w = "no_op"
down = "no_op"
h = "no_op"
H = "no_op"
j = "jump_view_left"
J = "swap_view_left"
k = "jump_view_down"
K = "swap_view_down"
l = "jump_view_up"
L = "swap_view_up"
left = "no_op"
right = "no_op"
up = "no_op"

[keys.select.z]
backspace = "no_op"
down = "no_op"
pagedown = "no_op"
pageup = "no_op"
space = "no_op"
up = "no_op"
z = "no_op"

[keys.select.Z]
backspace = "no_op"
down = "no_op"
pagedown = "no_op"
pageup = "no_op"
space = "no_op"
up = "no_op"
z = "no_op"
