---
- name: Install MuseScore for FreeBSD
  become: true
  community.general.pkgng:
    name: musescore
  when: ansible_system == "FreeBSD"

- name: Install MuseScore for Linux
  ansible.builtin.package:
    name: musescore
  become: true
  ignore_errors: true
  register: musescore_linux
  when: ansible_system == "Linux"

- name: Install MuseScore for Linux
  become: true
  community.general.flatpak:
    name: org.musescore.MuseScore
  when: ansible_system == "Linux" and musescore_linux is failed

- name: Install MuseScore for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: musescore
    state: present
  when: ansible_system == "Darwin"

- name: Install MuseScore for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: musescore
  when: ansible_system == "Win32NT"
