---
- name: Install Bats for FreeBSD
  become: true
  community.general.pkgng:
    name: bats-core
  when: ansible_system == "FreeBSD"

- name: Install Bats for Linux
  ansible.builtin.package:
    name: bats
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "opkg"

- name: Install Bats for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: bats-core
  when: ansible_system == "Darwin"
