---
- name: Install Duf for Alpine
  become: true
  community.general.apk:
    name: duf
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "apk"

- name: Install Duf for FreeBSD
  become: true
  community.general.pkgng:
    name: duf
  when: ansible_system == "FreeBSD"

- name: Install Duf for Linux
  ansible.builtin.package:
    name: duf
  become: true
  ignore_errors: true
  register: duf_linux
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Get latest Duf version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/duf.json
  register: duf_formula
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr != "apk" and duf_linux is
    failed

- name: Download Duf for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/muesli/duf/releases/download/v{{
      duf_formula.json.versions.stable }}/duf_{{
      duf_formula.json.versions.stable }}_linux_{{ duf_arch[system_architecture]
      }}.tar.gz
  vars:
    duf_arch:
      amd64: x86_64
      arm64: arm64
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr != "apk" and duf_linux is
    failed

- name: Install Duf for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/duf
    force: true
    mode: "755"
    remote_src: true
    src: /tmp/duf
  become: true
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr != "apk" and duf_linux is
    failed

- name: Install Duf for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: duf
  when: ansible_system == "Darwin"

- name: Install Duf for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: duf
  when: ansible_system == "Win32NT"
