---
- name: Install RClone for FreeBSD
  become: true
  community.general.pkgng:
    name: rclone
  when: ansible_system == "FreeBSD"

- name: Install RClone for Linux
  ansible.builtin.package:
    name: rclone
    state: present
  become: true
  when: ansible_system == "Linux"

- name: Install RClone for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: rclone
  when: ansible_system == "Darwin"

- name: Install RClone for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: rclone
  when: ansible_system == "Win32NT"
