---
- name: Install audio packages for Alpine
  become: true
  community.general.apk:
    name:
      - alsa-lib
      - alsa-utils
      - ffmpeg
      - mediainfo
      - mpv
      - sox
  when: ansible_pkg_mgr == "apk"

- name: Install audio packages for Arch
  become: true
  community.general.pacman:
    name:
      - alsa-lib
      - alsa-utils
      - ffmpeg
      - mediainfo
      - mpv
      - sox
  when: ansible_pkg_mgr == "pacman"

- name: Install audio packages for Debian
  ansible.builtin.apt:
    name:
      - alsa-utils
      - libasound2-dev
      - ffmpeg
      - mediainfo
      - mpv
      - sox
  become: true
  when: ansible_pkg_mgr == "apt"

- name: Install audio packages for Fedora
  ansible.builtin.dnf:
    name:
      - alsa-lib
      - alsa-utils
      - mediainfo
      - mpv
      - sox
  become: true
  when: ansible_pkg_mgr in ["dnf", "dnf5"]

- name: Install audio packages for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - alsa-lib
      - alsa-utils
      - ffmpeg
      - mediainfo
      - mpv
      - sox
  when: ansible_system == "FreeBSD"

- name: Install audio packages for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name:
      - ffmpeg
      - media-info
      - mpv
      - sox
  when: ansible_system == "Darwin"

- name: Install audio packages for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name:
      - ffmpeg
      - mediainfo
      - mpv
      - sox
  when: ansible_system == "Win32NT"
