---
- name: Get latest Kubeshark version for Unix
  ansible.builtin.uri:
    headers: "{{ github_api_headers }}"
    method: GET
    return_content: true
    url: https://api.github.com/repos/kubeshark/kubeshark/releases/latest
  register: kubeshark_release_unix
  when: ansible_system in ["Darwin", "Linux"]

- name: Install Kubeshark for Unix
  ansible.builtin.get_url:
    dest: /usr/local/bin/kubeshark
    force: true
    mode: "755"
    url: >-
      https://github.com/kubeshark/kubeshark/releases/download/{{
      kubeshark_release_unix.json.tag_name }}/kubeshark_{{ ansible_system |
      lower }}_{{ system_architecture }}
  become: true
  when: ansible_system in ["Darwin", "Linux"]

- name: Get latest Kubeshark version for Windows
  ansible.windows.win_uri:
    headers: "{{ github_api_headers }}"
    method: GET
    return_content: true
    url: https://api.github.com/repos/kubeshark/kubeshark/releases/latest
  register: kubeshark_release_windows
  when: ansible_system == "Win32NT"

- name: Create Kubeshark program directory for Windows
  ansible.windows.win_file:
    path: "C:/Program Files/Kubeshark"
    state: directory
  when: ansible_system == "Win32NT"

- name: Update system path to include Kubeshark program directory for Windows
  ansible.windows.win_path:
    elements: "C:\\Program Files\\Kubeshark"
    scope: machine
  when: ansible_system == "Win32NT"

- name: Install Kubeshark for Windows
  ansible.windows.win_get_url:
    dest: "C:/Program Files/Kubeshark/kubeshark.exe"
    url: >-
      https://github.com/kubeshark/kubeshark/releases/download/{{
      kubeshark_release_windows.json.tag_name }}/kubeshark.exe
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system in ["Darwin", "Linux"]

- name: Create Kubeshark shell completions for Unix
  ansible.builtin.shell:
    cmd: kubeshark completion {{ item }} > /tmp/kubeshark.{{ item }}
  become: true
  changed_when: true
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  loop:
    - bash
    - fish
  when: ansible_system in ["Darwin", "Linux"]

- name: Install Kubeshark shell completions for Unix
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: /tmp/kubeshark.{{ item.shell }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/kubeshark"
      shell: bash
    - dest: "{{ fish_completion }}/kubeshark.fish"
      shell: fish
  when: ansible_system in ["Darwin", "Linux"]
