---
helm_plugins_:
  always: []
  Darwin:
    - https://github.com/aslafy-z/helm-git
    - https://github.com/databus23/helm-diff
    - https://github.com/jkroepke/helm-secrets
  FreeBSD: []
  Linux:
    - https://github.com/aslafy-z/helm-git
    - https://github.com/databus23/helm-diff
    - https://github.com/jkroepke/helm-secrets
  Win32NT:
    - https://github.com/aslafy-z/helm-git
    - https://github.com/jkroepke/helm-secrets
helm_plugins: >-
  {{ helm_plugins_.always + helm_plugins_.get(ansible_system, []) }}
