---
- name: Install JQ for FreeBSD
  become: true
  community.general.pkgng:
    name: jq
  when: ansible_system == "FreeBSD"

- name: Install JQ for Linux
  ansible.builtin.package:
    name: jq
  become: true
  when: ansible_system == "Linux"

- name: Install JQ for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: jq
  when: ansible_system == "Darwin"

- name: Install JQ for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: jq
  when: ansible_system == "Win32NT"
