---
- name: Install Beekeeper for Linux
  become: true
  community.general.flatpak:
    name: io.beekeeperstudio.Studio
  when: ansible_system == "Linux"

- name: Install Beekeeper for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: beekeeper-studio
    state: present
  when: ansible_system == "Darwin"

- name: Install Beekeeper for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: beekeeper-studio
  when: ansible_system == "Win32NT"
