---
- name: Install Flatpak for Linux
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true
  when: ansible_system == "Linux"

- name: Add Flathub remote repository for Linux
  ansible.builtin.command: >-
    flatpak remote-add --if-not-exists flathub
    https://flathub.org/repo/flathub.flatpakrepo
  become: true
  # Command does not provide stdout information to determine a change.
  changed_when: true
  when: ansible_system == "Linux"

- name: Enable Flathub remote repository for Linux
  ansible.builtin.command: flatpak remote-modify --enable flathub
  become: true
  # Command does not provide stdout information to determine a change.
  changed_when: true
  when: ansible_system == "Linux"

- name: Install Flatpak packages for Linux
  become: true
  community.general.flatpak:
    name: "{{ item }}"
  loop: "{{ flatpak_packages }}"
  when: ansible_system == "Linux"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    flatpak_role_executed: true
