---
- name: Install Dust for FreeBSD
  become: true
  community.general.pkgng:
    name: dust
  when: ansible_system == "FreeBSD"

- name: Get latest Dust version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/dust.json
  register: dust_formula
  when: ansible_system == "Linux"

- name: Download Dust for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/bootandy/dust/releases/download/v{{
      dust_formula.json.versions.stable }}/dust-v{{
      dust_formula.json.versions.stable }}-{{ dust_arch }}-unknown-linux-{{
      system_libc }}.tar.gz
  when: ansible_system == "Linux"

- name: Install Dust for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/dust
    force: true
    mode: "755"
    remote_src: true
    src: >-
      /tmp/dust-v{{ dust_formula.json.versions.stable }}-{{ dust_arch
      }}-unknown-linux-{{ system_libc }}/dust
  become: true
  when: ansible_system == "Linux"

- name: Install Dust for MacOS
  community.general.homebrew:
    name: dust
  when: ansible_system == "Darwin"

- name: Install Dust for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: dust
  when: ansible_system == "Win32NT"

- name: Create Dust settings directory for Unix
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/dust"
    state: directory
  become: true
  when: ansible_system != "Win32NT"

- name: Create Dust settings directory for Windows
  ansible.windows.win_file:
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/dust"
    state: directory
  when: ansible_system == "Win32NT"

- name: Copy Dust settings file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/dust/config.toml"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: config.toml
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Dust settings file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}/.config/dust/config.toml"
    force: true
    owner: "{{ user_id }}"
    src: config.toml
  when: ansible_system == "Win32NT"
