---
- name: Install SQLite for FreeBSD
  become: true
  community.general.pkgng:
    name: sqlite3
  when: ansible_system == "FreeBSD"

- name: Install SQLite for Linux
  ansible.builtin.package:
    name: "{{ sqlite_package.get(ansible_pkg_mgr, 'sqlite') }}"
  become: true
  vars:
    sqlite_package:
      apt: sqlite3
      opkg: sqlite3-cli
  when: ansible_system == "Linux"

- name: Install SQLite for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: sqlite
  when: ansible_system == "Darwin"

- name: Install SQLite for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: sqlite
  when: ansible_system == "Win32NT"

- name: Copy SQLite settings file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.sqliterc"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: sqliterc
  become: true
  when: ansible_system != "Win32NT"

- name: Copy SQLite settings file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}/.sqliterc"
    force: true
    owner: "{{ user_id }}"
    src: sqliterc
  when: ansible_system == "Win32NT"
