---
- name: Get latest MongoDB Compass version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/cask/mongodb-compass.json
  register: compass_cask_linux
  when:
    ansible_pkg_mgr in ["apt", "dnf", "dnf5"] and system_architecture == "amd64"

- name: Install MongoDB Compass For Debian
  ansible.builtin.apt:
    deb: >-
      https://downloads.mongodb.com/compass/mongodb-compass_{{
      compass_cask_linux.json.version }}_amd64.deb
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install MongoDB Compass For Fedora
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: >-
      https://downloads.mongodb.com/compass/mongodb-compass-{{
      compass_cask_linux.json.version }}.x86_64.rpm
  become: true
  when: ansible_pkg_mgr in ["dnf", "dnf5"] and system_architecture == "amd64"

- name: Install MongoDB Compass for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: mongodb-compass
    state: present
  when: ansible_system == "Darwin"

- name: Get latest MongoDB Compass version for Windows
  ansible.windows.win_uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/cask/mongodb-compass.json
  register: compass_cask_windows
  when: ansible_system == "Win32NT"

- name: Install MongoDB Compass for Windows
  ansible.windows.win_package:
    path: >-
      https://downloads.mongodb.com/compass/mongodb-compass-{{
      compass_cask_windows.json.version }}-win32-x64.msi
  when: ansible_system == "Win32NT"
