---
- name: Install Bash for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - bash
      - bash-completion
  when: ansible_system == "FreeBSD"

- name: Install Bash for Linux
  ansible.builtin.package:
    name:
      - bash
      - bash-completion
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "opkg"

- name: Install Bash for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name:
      - bash
      - bash-completion@2
  when: ansible_system == "Darwin"

- name: Install Bash for OpenWrt
  ansible.builtin.package:
    name: bash
  become: true
  when: ansible_pkg_mgr == "opkg"

- name: Register Bash as a valid login shell
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ bash_executable }}"
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Bash non-login settings file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.bashrc"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: bashrc
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Bash login settings file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.bash_profile"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: bash_profile
  become: true
  when: ansible_system != "Win32NT"

- name: Register Bash as a valid login shell
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ bash_executable }}"
  become: true
  when: ansible_system != "Win32NT"

- name: Install Shadow for Alpine
  become: true
  community.general.apk:
    name: shadow
  when: ansible_pkg_mgr == "apk" and user_login == "bash"

- name: Install Shadow for OpenWrt
  become: true
  community.general.opkg:
    name: shadow-usermod
  when: ansible_pkg_mgr == "opkg" and user_login == "bash"

# User shell is not updated on Alpine Linux when using Ansible user module.
# Workaround comes from https://github.com/ansible/ansible/issues/61911.
- name: Change user default shell to Bash for Alpine
  ansible.builtin.command:
    cmd: chsh -s {{ bash_executable }} {{ user_id }}
  become: true
  changed_when: true
  when: ansible_pkg_mgr == "apk" and user_login == "bash"

- name: Change user default shell to Bash for Unix
  ansible.builtin.user:
    name: "{{ user_id }}"
    shell: "{{ bash_executable }}"
  become: true
  when: >-
    ansible_system != "Win32NT" and ansible_pkg_mgr != "apk" and user_login ==
    "bash"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    bash_role_executed: true
