---
- name: Install DBeaver for Linux
  become: true
  community.general.flatpak:
    name: io.dbeaver.DBeaverCommunity
  when: ansible_system == "Linux"

- name: Install DBeaver for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: dbeaver-community
    state: present
  when: ansible_system == "Darwin"

- name: Install DBeaver for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: dbeaver
  when: ansible_system == "Win32NT"
