---
- name: Get latest TLDR version for Unix
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/tealdeer.json
  register: tldr_formula
  when: ansible_system != "Win32NT"

- name: Install TLDR for FreeBSD
  become: true
  community.general.pkgng:
    name: tealdeer
  when: ansible_system == "FreeBSD"

- name: Install TLDR for Linux
  ansible.builtin.get_url:
    dest: /usr/local/bin/tldr
    force: true
    mode: "755"
    url: >-
      https://github.com/dbrgn/tealdeer/releases/download/v{{
      tldr_formula.json.versions.stable }}/tealdeer-linux-{{
      tldr_arch[system_architecture] }}
  become: true
  vars:
    tldr_arch:
      amd64: x86_64-musl
      arm64: arm-musleabihf
  when: ansible_system == "Linux"

- name: Install TLDR for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: tealdeer
  when: ansible_system == "Darwin"

- name: Install TDLR for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: tealdeer
  when: ansible_system == "Win32NT"

- name: Create TLDR repository directory for Linux
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.local/share"
    state: directory
  become: true
  when: ansible_system == "Linux"

- name: Update TLDR documentation for Unix
  ansible.builtin.command: tldr --update
  become: true
  become_user: "{{ user_id }}"
  changed_when: "'Successfully updated' in tldr_update"
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  register: tldr_update
  when: ansible_system != "Win32NT"

- name: Update TLDR documentation for Windows
  ansible.windows.win_command: tldr --update
  changed_when: "'Successfully updated' in tldr_update"
  environment:
    Path: "{{ scoop_apps }}\\tealdeer\\current;{{ ansible_env.Path }}"
  register: tldr_update
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system != "Win32NT"

- name: Install TLDR shell completions for Unix
  ansible.builtin.get_url:
    dest: "{{ item.dest }}"
    mode: "644"
    url: >-
      https://github.com/dbrgn/tealdeer/releases/download/v{{
      tldr_formula.json.versions.stable }}/completions_{{ item.shell }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/tldr"
      shell: bash
    - dest: "{{ fish_completion }}/tldr.fish"
      shell: fish
  when: ansible_system != "Win32NT"
