---
- name: Enable Forge extension for GNOME desktops
  block:
    - name: Enable Forge extension for GNOME desktops
      ansible.builtin.command: gnome-extensions enable forge@jmmaranan.com
      become: true
      become_user: "{{ user_id }}"
      # Command does not provide stdout information to determine a change.
      changed_when: true

    - name: Change Forge settings for GNOME desktops
      ansible.builtin.script: forge.sh
      become: true
      become_user: "{{ user_id }}"
  rescue:
    - name: Get latest Forge extension version for GNOME desktops
      ansible.builtin.uri:
        method: GET
        return_content: true
        url: >-
          https://extensions.gnome.org/extension-info/?uuid=forge@jmmaranan.com&shell_version={{
          gnome_version }}
      register: window_manager_forge_release

    - name: Download Forge extension for GNOME desktops
      ansible.builtin.get_url:
        dest: /tmp/forge_extension.zip
        mode: "644"
        url:
          https://extensions.gnome.org{{
          window_manager_forge_release.json.download_url }}

    - name: Install Forge extension for GNOME desktops
      ansible.builtin.command: >-
        gnome-extensions install /tmp/forge_extension.zip
      become: true
      become_user: "{{ user_id }}"
      # Command does not provide stdout information to determine a change.
      changed_when: true

    - name: Notify user to log and back in
      ansible.builtin.fail:
        msg: >-
          Enabling Forge extension may require a desktop session restart. Please
          log out of your current user session and log back in. Then execute
          this role again.
