---
- name: Install GDU for Alpine
  become: true
  community.general.apk:
    name: gdu
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/community
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "apk"

- name: Install GDU for FreeBSD
  become: true
  community.general.pkgng:
    name: gdu
  when: ansible_system == "FreeBSD"

- name: Install GDU for Linux
  ansible.builtin.package:
    name: gdu
  become: true
  ignore_errors: true
  register: gdu_linux
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Get latest GDU version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/gdu.json
  register: gdu_formula
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr != "apk" and gdu_linux is
    failed

- name: Download GDU for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/dundee/gdu/releases/download/v{{
      gdu_formula.json.versions.stable }}/gdu_linux_{{ system_architecture
      }}.tgz
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr != "apk" and gdu_linux is
    failed

- name: Install GDU for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/gdu
    force: true
    mode: "755"
    remote_src: true
    src: /tmp/gdu_linux_{{ system_architecture }}
  become: true
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr != "apk" and gdu_linux is
    failed

- name: Install GDU for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: gdu
  when: ansible_system == "Darwin"

- name: Install GDU for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: gdu
  when: ansible_system == "Win32NT"
