---
nushell_arch_:
  amd64: x86_64
  arm64: aarch64
nushell_arch: "{{ nushell_arch_[system_architecture] }}"
nushell_libc: >-
  {{ 'gnu' if glibc_version is defined and glibc_version is
  ansible.builtin.version("2.35", ">") else 'musl' }}
