---
- name: Install desktop management dependencies for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - dconf-editor
      - xdg-utils
  when: ansible_system == "FreeBSD" and gnome_desktop

- name: Install desktop management dependencies for Linux
  ansible.builtin.package:
    name:
      - dconf-editor
      - xdg-utils
  become: true
  when: ansible_system == "Linux" and gnome_desktop

- name: Add clipboard commands for Linux
  ansible.builtin.package:
    name: wl-clipboard
  become: true
  failed_when: false
  when: ansible_system == "Linux"

- name: Install desktop management dependencies for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: duti
  when: ansible_system == "Darwin"

- name: Install desktop management dependencies for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: powertoys
  when: ansible_system == "Win32NT"

- name: Create keyboard layout directory for MacOS
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "700"
    owner: "{{ user_id }}"
    path: "{{ user_home }}/Library/Keyboard Layouts"
    state: directory
  become: true
  when: ansible_system == "Darwin"

# Custom keyboard layout disable special "alt" characters that interfere with
# "alt" keybindings. Soluation was taken from
# https://stackoverflow.com/a/16019737.
- name: Copy keyboard layout for MacOS
  ansible.builtin.copy:
    dest: "{{ user_home }}/Library/Keyboard Layouts/no_alt_characters.keylayout"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: no_alt_characters.keylayout
  become: true
  when: ansible_system == "Darwin"

- name: Change desktop settings for GNOME desktops
  ansible.builtin.script: gnome.sh
  become: true
  become_user: "{{ user_id }}"
  when: ansible_system in ["FreeBSD", "Linux"] and gnome_desktop

- name: Change desktop settings for MacOS
  ansible.builtin.script: macos.sh
  become: true
  become_user: "{{ user_id }}"
  when: ansible_system == "Darwin"

- name: Change desktop settings for Windows
  ansible.builtin.script: windows.ps1
  when: ansible_system == "Win32NT"

##### Distribution specific desktop setting overrides. #####

- name: Change desktop settings for Fedora
  ansible.builtin.script: fedora.sh
  become: true
  become_user: "{{ user_id }}"
  when: ansible_distribution =="Fedora" and gnome_desktop

- name: Change desktop settings for PopOS
  ansible.builtin.script: popos.sh
  become: true
  become_user: "{{ user_id }}"
  when: ansible_distribution == "Pop!_OS" and gnome_desktop

- name: Change desktop settings for Ubuntu
  ansible.builtin.script: ubuntu.sh
  become: true
  become_user: "{{ user_id }}"
  when: ansible_distribution == "Ubuntu" and gnome_desktop
