---
- name: Install Git for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - git
      - git-delta
      - git-lfs
  when: ansible_system == "FreeBSD"

- name: Install Git for Linux
  ansible.builtin.package:
    name:
      - git
      - git-lfs
  become: true
  when: ansible_system == "Linux"

- name: Install Git Delta for Linux
  ansible.builtin.package:
    name: git-delta
  become: true
  ignore_errors: true
  register: git_delta_linux
  when: ansible_system == "Linux"

- name: Get latest Git Delta version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/git-delta.json
  register: git_delta_formula
  when: >-
    ansible_system == "Linux" and (system_libc == "gnu" or system_architecture
    == "amd64") and git_delta_linux is failed

- name: Download Git Delta for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "755"
    remote_src: true
    src: >-
      https://github.com/dandavison/delta/releases/download/{{
      git_delta_formula.json.versions.stable }}/delta-{{
      git_delta_formula.json.versions.stable }}-{{ git_delta_arch
      }}-unknown-linux-{{ system_libc }}.tar.gz
  when: >-
    ansible_system == "Linux" and (system_libc == "gnu" or system_architecture
    == "amd64") and git_delta_linux is failed

- name: Install Git Delta for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/delta
    force: true
    mode: "755"
    remote_src: true
    src: >-
      /tmp/delta-{{ git_delta_formula.json.versions.stable }}-{{ git_delta_arch
      }}-unknown-linux-{{ system_libc }}/delta
  become: true
  when: >-
    ansible_system == "Linux" and (system_libc == "gnu" or system_architecture
    == "amd64") and git_delta_linux is failed

- name: Install Git for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name:
      - git
      - git-delta
      - git-lfs
  when: ansible_system == "Darwin"

- name: Install Git HTTP for OpenWrt
  community.general.opkg:
    name: git-http
  become: true
  when: ansible_pkg_mgr == "opkg"

- name: Install Git for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name:
      - delta
      - git-lfs
      - mingit
      - posh-git
  when: ansible_system == "Win32NT"

- name: Copy Git configuration file for Unix
  ansible.builtin.template:
    dest: "{{ user_home }}/.gitconfig"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: gitconfig.j2
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Git configuration file for Windows
  ansible.windows.win_template:
    dest: "{{ user_home }}/.gitconfig"
    force: true
    owner: "{{ user_id }}"
    src: gitconfig.j2
  when: ansible_system == "Win32NT"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    git_role_executed: true
