---
- name: Install Sops for FreeBSD
  become: true
  community.general.pkgng:
    name: sops
  when: ansible_system == "FreeBSD"

- name: Install Sops for Linux
  ansible.builtin.package:
    name: sops
  become: true
  ignore_errors: true
  register: sops_linux
  when: ansible_system == "Linux"

- name: Get latest Sops version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/sops.json
  register: sops_formula
  when: ansible_system == "Linux" and sops_linux is failed

- name: Install Sops for Linux
  ansible.builtin.get_url:
    dest: /usr/local/bin/sops
    force: true
    mode: "755"
    url: >-
      https://github.com/mozilla/sops/releases/download/v{{
      sops_formula.json.versions.stable }}/sops-v{{
      sops_formula.json.versions.stable }}.linux.{{ system_architecture }}
  become: true
  when: ansible_system == "Linux" and sops_linux is failed

- name: Install Sops for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: sops
  when: ansible_system == "Darwin"

- name: Install Sops for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: sops
  when: ansible_system == "Win32NT"
