---
- name: Get latest Watchexec version for Unix
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/watchexec.json
  register: watchexec_formula
  when: ansible_system in ["Darwin", "Linux"]

- name: Download Watchexec for Unix
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/watchexec/watchexec/releases/download/v{{
      watchexec_formula.json.versions.stable }}/watchexec-{{
      watchexec_formula.json.versions.stable }}-{{ watchexec_arch }}-{{
      watchexec_env }}.tar.xz
  when: ansible_system in ["Darwin", "Linux"]

- name: Install Watchexec for Linux
  ansible.builtin.package:
    name: watchexec
  become: true
  ignore_errors: true
  register: watchexec_linux
  when: ansible_system == "Linux"

- name: Install Watchexec for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/watchexec
    force: true
    mode: "755"
    remote_src: true
    src: >-
      /tmp/watchexec-{{ watchexec_formula.json.versions.stable }}-{{
      watchexec_arch }}-{{ watchexec_env }}/watchexec
  become: true
  when: ansible_system == "Linux" and watchexec_linux is failed

- name: Install Watchexec for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: watchexec
  when: ansible_system == "Darwin"

- name: Install Watchexec for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: watchexec
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system in ["Darwin", "Linux"]

- name: Install Watchexec shell completions for Unix
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: >-
      /tmp/watchexec-{{ watchexec_formula.json.versions.stable }}-{{
      watchexec_arch }}-{{ watchexec_env }}/completions/{{ item.shell }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/watchexec"
      shell: bash
    - dest: "{{ fish_completion }}/watchexec.fish"
      shell: fish
  when: ansible_system in ["Darwin", "Linux"]
