---
- name: Copy Readline configuration file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.inputrc"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: inputrc
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Readline configuration file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}/.inputrc"
    force: true
    owner: "{{ user_id }}"
    src: inputrc
  when: ansible_system == "Win32NT"
