---
- name: Install Digital Ocean CLI for FreeBSD
  become: true
  community.general.pkgng:
    name: doctl
  when: ansible_system == "FreeBSD"

- name: Install Digital Ocean CLI for Linux
  ansible.builtin.package:
    name: doctl
  become: true
  ignore_errors: true
  register: doctl_linux
  when: ansible_system == "Linux"

- name: Get latest Digital Ocean CLI version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/doctl.json
  register: doctl_formula
  when: ansible_system == "Linux" and doctl_linux is failed

- name: Download Digital Ocean CLI for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/digitalocean/doctl/releases/download/v{{
      doctl_formula.json.versions.stable }}/doctl-{{
      doctl_formula.json.versions.stable }}-linux-{{ system_architecture
      }}.tar.gz
  when: ansible_system == "Linux" and doctl_linux is failed

- name: Install Digital Ocean CLI for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/doctl
    force: true
    mode: "755"
    remote_src: true
    src: /tmp/doctl
  become: true
  when: ansible_system == "Linux" and doctl_linux is failed

- name: Install Digital Ocean CLI for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: doctl
  when: ansible_system == "Darwin"

- name: Install Digital Ocean CLI for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: doctl
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system != "Win32NT"

- name: Create Digital Ocean CLI shell completions for Unix
  ansible.builtin.shell:
    cmd: doctl completion {{ item }} > /tmp/doctl.{{ item }}
  become: true
  changed_when: true
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  loop:
    - bash
    - fish
  when: ansible_system != "Win32NT"

- name: Install Digital Ocean CLI shell completions for Unix
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: /tmp/doctl.{{ item.shell }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/doctl"
      shell: bash
    - dest: "{{ fish_completion }}/doctl.fish"
      shell: fish
  when: ansible_system != "Win32NT"
