---
- name: Install AWSCLI for FreeBSD
  become: true
  community.general.pkgng:
    name: py311-awscli
  when: ansible_system == "FreeBSD"

- name: Install AWSCLI for Alpine
  become: true
  community.general.apk:
    name: aws-cli
  when: ansible_pkg_mgr == "apk"

- name: Download AWSCLI for Linux
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://awscli.amazonaws.com/awscli-exe-linux-{{
      awscli_arch[system_architecture] }}.zip
  vars:
    awscli_arch:
      amd64: x86_64
      arm64: aarch64
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install AWSCLI for Linux
  ansible.builtin.command:
    cmd: /tmp/aws/install --update
  become: true
  changed_when: "'Found same AWS CLI version' not in aws_install"
  register: aws_install
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install AWSCLI for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: awscli
  when: ansible_system == "Darwin"

- name: Install AWSCLI for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: aws
  when: ansible_system == "Win32NT"
