# Ansible Galaxy collection metadata file.
#
# For more information, visit
# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta.

---
authors:
  - Macklan Weinstein <macklan.weinstein@gmail.com>
build_ignore:
  - __pycache__
  - .DS_Store
  - .dockerignore
  - .editorconfig
  - .github
  - .shellcheckrc
  - .venv
  - completions
  - docs
  - node_modules
  - package-lock.json
  - package.json
  - poetry.lock
  - PSScriptAnalyzerSettings.psd1
  - pyproject.toml
  - scripts
  - tests
  - tmp
dependencies:
  chocolatey.chocolatey: ">=1.1.0"
  community.general: ">=4.0.0"
  community.windows: ">=1.9.0"
description: software installers
documentation: http://scruffaluff.github.io/bootware
homepage: http://github.com/scruffaluff/bootware
issues: http://github.com/scruffaluff/bootware/issues
license:
  - MIT
name: bootware
namespace: scruffaluff
readme: README.md
repository: http://github.com/scruffaluff/bootware
tags:
  - install
  - linux
  - tools
  - windows
version: "0.8.3"
