---
# TODO: Renable when Fzf package in most distributions reaches version 0.48.0.
# - name: Install FzF for FreeBSD
#   become: true
#   community.general.pkgng:
#     name: fzf
#   when: ansible_system == "FreeBSD"
#
# - name: Install Fzf for Linux
#   ansible.builtin.package:
#     name: fzf
#   become: true
#   ignore_errors: true
#   register: fzf_linux
#   when: ansible_system == "Linux"

- name: Get latest Fzf version for Unix
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/fzf.json
  register: fzf_formula
  when: ansible_system in ["FreeBSD", "Linux"]

# Some of the Fzf releases have a "v" in the name while others do not.
#
# The ignore_errors, loop, and vars allow for trying mutliple URLs and breaking
# the loop if a URL succeeds. Since ignore_errors is false on the last loop
# item, the task will fail if none of the URLs work.
- name: Install Fzf for Unix
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/junegunn/fzf/releases/download/{{ item }}{{
      fzf_formula.json.versions.stable }}/fzf-{{
      fzf_formula.json.versions.stable }}-{{ ansible_system | lower }}_{{
      system_architecture }}.tar.gz
  ignore_errors: "{{ item != 'v' }}"
  loop:
    - ""
    - v
  register: fzf_unarchive_result
  vars:
    fzf_unarchive_run: >-
      {{ (fzf_unarchive_result is failed) if fzf_unarchive_result is defined
      else true }}
  when: ansible_system in ["FreeBSD", "Linux"] and fzf_unarchive_run

- name: Install Fzf for Unix
  ansible.builtin.copy:
    dest: /usr/local/bin/fzf
    force: true
    mode: "755"
    remote_src: true
    src: /tmp/fzf
  become: true
  when: ansible_system in ["FreeBSD", "Linux"]

- name: Install FzF for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name:
      - fzf
      - tree
  when: ansible_system == "Darwin"

- name: Install FzF for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name:
      - fzf
      - psfzf
  when: ansible_system == "Win32NT"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    fzf_role_executed: true
