---
- name: Get latest Lsd version for Unix
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/lsd.json
  register: lsd_formula
  when: ansible_system != "Win32NT"

- name: Install Lsd for FreeBSD
  become: true
  community.general.pkgng:
    name: lsd
  when: ansible_system == "FreeBSD"

- name: Download Lsd for Unix
  ansible.builtin.unarchive:
    dest: /tmp
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/lsd-rs/lsd/releases/download/v{{
      lsd_formula.json.versions.stable }}/lsd-v{{
      lsd_formula.json.versions.stable }}-{{ lsd_arch }}-unknown-linux-{{
      lsd_libc }}.tar.gz
  when: ansible_system != "Win32NT"

- name: Install Lsd for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/lsd
    force: true
    mode: "755"
    remote_src: true
    src: >-
      /tmp/lsd-v{{ lsd_formula.json.versions.stable }}-{{ lsd_arch
      }}-unknown-linux-{{ lsd_libc }}/lsd
  become: true
  when: ansible_system == "Linux"

- name: Install Lsd for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: lsd
  when: ansible_system == "Darwin"

- name: Install Lsd for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: lsd
  when: ansible_system == "Win32NT"

- name: Copy Ls colors file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.ls_colors"
    force: true
    group: "{{ group_id }}"
    mode: "640"
    owner: "{{ user_id }}"
    src: ls_colors
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Ls colors file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}/.ls_colors"
    force: true
    owner: "{{ user_id }}"
    src: ls_colors
  when: ansible_system == "Win32NT"

- name: Create Lsd configuration directory for Unix
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/lsd"
    state: directory
  become: true
  when: ansible_system != "Win32NT"

- name: Copy Lsd configuration files for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/lsd/{{ item }}"
    force: true
    group: "{{ group_id }}"
    mode: "644"
    owner: "{{ user_id }}"
    src: "{{ item }}"
  become: true
  loop:
    - colors.yaml
    - config.yaml
  when: ansible_system != "Win32NT"

- name: Create Lsd configuration directory for Windows
  ansible.windows.win_file:
    owner: "{{ user_id }}"
    path: "{{ user_home }}/AppData/Roaming/lsd"
    state: directory
  when: ansible_system == "Win32NT"

- name: Copy Lsd configuration files for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}/AppData/Roaming/lsd/{{ item }}"
    force: true
    owner: "{{ user_id }}"
    src: "{{ item }}"
  loop:
    - colors.yaml
    - config.yaml
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system != "Win32NT"

- name: Install Lsd shell completions for Unix
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: >-
      /tmp/lsd-v{{ lsd_formula.json.versions.stable }}-{{ lsd_arch
      }}-unknown-linux-{{ lsd_libc }}/autocomplete/lsd.{{ item.extension }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/lsd"
      extension: bash-completion
    - dest: "{{ fish_completion }}/lsd.fish"
      extension: fish
  when: ansible_system != "Win32NT"
