---
github_runner_arch_:
  amd64: x64
  arm64: arm64
github_runner_folder_:
  Darwin: /Users/github-runner
  Win32NT: C:/Users/github-runner
github_runner_arch: "{{ github_runner_arch_[system_architecture] }}"
github_runner_folder: >-
  {{ github_runner_folder_.get(ansible_system, '/home/github-runner')
  }}/.local/github-runner
