---
- name: Install fonts for Unix
  ansible.builtin.include_tasks: unix.yaml
  loop: "{{ font_families }}"
  loop_control:
    loop_var: font_family
  vars:
    font_folder:
      FreeBSD: /usr/local/share/fonts/{{ font_family.name }}
      Darwin: /Library/Fonts
      Linux: /usr/share/fonts/{{ font_family.name }}
  when: ansible_system != "Win32NT"

- name: Update font cache for Unix
  ansible.builtin.command:
    cmd: fc-cache --verbose
  become: true
  changed_when: "'new cache contents' in font_cache_unix"
  register: font_cache_unix
  when: ansible_system in ["FreeBSD", "Linux"]

- name: Install fonts for Windows
  ansible.builtin.include_tasks: windows.yaml
  loop: "{{ font_families }}"
  loop_control:
    loop_var: font_family
  vars:
    font_folder: "C:\\Windows\\Fonts"
  when: ansible_system == "Win32NT"
