---
- name: Check if font is installed for Windows
  ansible.windows.win_stat:
    path: "{{ font_folder }}/{{ font_family.check }}"
  register: font_check_windows

- name: Install fonts for Windows
  when: not font_check_windows.stat.exists
  block:
    - name: Download font archives for Windows
      ansible.windows.win_get_url:
        dest: "{{ ansible_env.TEMP }}/{{ font_family.name }}.zip"
        url: "{{ font_family.url }}"

    - name: Decompress font archives for Windows
      community.windows.win_unzip:
        dest: "{{ ansible_env.TEMP }}/{{ font_family.name }}"
        src: "{{ ansible_env.TEMP }}/{{ font_family.name }}.zip"

    # Based on logic from
    # https://www.alkanesolutions.co.uk/2021/12/06/installing-fonts-with-powershell.
    # Do not quote $Patterns variable, otherwise it will be interpreted as a
    # string instead of a list.
    - name: Install fonts for Windows
      ansible.windows.win_shell: |
        $ErrorActionPreference = 'Stop'
        $PSNativeCommandUseErrorActionPreference = $True
        [System.Reflection.Assembly]::LoadWithPartialName('PresentationFramework')
        Add-Type -PassThru -AssemblyName PresentationFramework | Out-Null
        $Folder = '{{ ansible_env.TEMP }}/{{ font_family.name }}'
        $Patterns = {{ font_family.patterns | map('quote') | join(',') }}
        ForEach ($File in Get-ChildItem -Recurse -Include $Patterns -Path $Folder) {
          $Glyph = [System.Windows.Media.GlyphTypeface]::new($File.FullName)
          $Family = $Glyph.Win32FamilyNames['en-us']
          If ($Family -Eq $Null) {
            $Family = $Glyph.Win32FamilyNames.Values.Item(0)
          }
          $Face = $Glyph.Win32FaceNames['en-us']
          If ($Face -Eq $Null) {
            $Face = $Glyph.Win32FaceNames.Values.Item(0)
          }
          $Font = ("$Family $Face").Trim()
          Switch ($File.Extension) {
            '.otf' {
              $Font = "$Font (OpenType)"
            }
            '.ttf' {
              $Font = "$Font (TrueType)"
            }
          }
          Copy-Item -Destination "{{ font_folder }}\$($Font.Name)" -Path "$File"
          New-ItemProperty -Force `
            -Name "$Font" `
            -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Fonts' `
            -PropertyType String `
            -Value $File.Name
        }
      changed_when: true
