---
dependencies:
  - role: variable
  - role: flatpak
    when: >-
      flatpak_role_executed is not defined and ansible_system == "Linux" and
      ansible_pkg_mgr not in ["apt", "dnf", "dnf5"] and system_architecture ==
      "amd64"
