---
- name: Get latest K3d version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/k3d.json
  register: k3d_formula
  when: ansible_system == "Linux"

- name: Install K3d for Linux
  ansible.builtin.get_url:
    dest: /usr/local/bin/k3d
    force: true
    mode: "755"
    url: >-
      https://github.com/k3d-io/k3d/releases/download/v{{
      k3d_formula.json.versions.stable }}/k3d-linux-{{ system_architecture }}
  become: true
  when: ansible_system == "Linux"

- name: Install K3d for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: k3d
  when: ansible_system == "Darwin"

- name: Install K3d for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: k3d
  when: ansible_system == "Win32NT"
