---
watchexec_libc: >-
  {{ 'gnu' if glibc_version is defined and glibc_version is
  ansible.builtin.version("2.39", ">") else 'musl' }}

watchexec_arch_:
  amd64: x86_64
  arm64: aarch64
watchexec_env_:
  Darwin: apple-darwin
  Linux: unknown-linux-{{ watchexec_libc }}
  Win32NT: pc-windows-msvc
watchexec_arch: "{{ watchexec_arch_[system_architecture] }}"
watchexec_env: "{{ watchexec_env_.get(ansible_system, 'unknown') }}"
