---
- name: Install Restic for FreeBSD
  become: true
  community.general.pkgng:
    name: restic
  when: ansible_system == "FreeBSD"

- name: Install Restic for Linux
  ansible.builtin.package:
    name: restic
  become: true
  when: ansible_system == "Linux"

- name: Install Restic for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: restic
  when: ansible_system == "Darwin"

- name: Install Restic for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: restic
  when: ansible_system == "Win32NT"

- name: Create shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion }}"
    - "{{ fish_completion }}"
  when: ansible_system != "Win32NT"

- name: Create Restic shell completions for Unix
  ansible.builtin.command:
    cmd: restic generate --{{ item }}-completion /tmp/restic.{{ item }}
  become: true
  changed_when: true
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  loop:
    - bash
    - fish
  when: ansible_system != "Win32NT"

- name: Install Restic shell completions for Unix
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: /tmp/restic.{{ item.shell }}
  become: true
  loop:
    - dest: "{{ bash_completion }}/restic"
      shell: bash
    - dest: "{{ fish_completion }}/restic.fish"
      shell: fish
  when: ansible_system != "Win32NT"
