---
- name: Install Sonic Pi for Linux
  become: true
  community.general.flatpak:
    name: net.sonic_pi.SonicPi
  when: ansible_system == "Linux"

- name: Install Sonic Pi for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: sonic-pi
    state: present
  when: ansible_system == "Darwin"

- name: Install Sonic Pi for Windows
  community.windows.win_scoop:
    global: "{{ scoop_global }}"
    name: sonic-pi
  when: ansible_system == "Win32NT"
