# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: test

# Makes workflow run on push or pull request to the main branch.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  fedora:
    name: Test bootstrapping software for Fedora Linux
    env:
      DOCKER_BUILD_SUMMARY: "false"
    # Fedora test fails in initial setup as of 01/18/2025 due to a "
    # Authentication service cannot retrieve authentication info" sudo error
    # which does not happen locally.
    runs-on: ubuntu-24.04
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: test=true
          context: .
          file: tests/integration/fedora.dockerfile
          platforms: linux/${{ inputs.platform || 'amd64' }}
          push: false
          tags: docker.io/scruffaluff/bootware:fedora
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
