# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: test

# Makes workflow run on push or pull request to the main branch.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean
      job:
        default: debian
        description: CI job to run
        options:
          - alpine
          - arch
          - debian
          - fedora
          - freebsd
          - macos
          - package
          - suse
          - ubuntu
          - windows
        type: choice
      platform:
        default: amd64
        description: Docker architecture platform
        options:
          - amd64
          - arm64
        type: choice

jobs:
  fedora:
    name: Test bootstrapping software for Fedora Linux
    env:
      DOCKER_BUILD_SUMMARY: "false"
    if: >-
      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'fedora' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: >-
          docker build --no-cache --build-arg test=true --file
          tests/integration/fedora.dockerfile --tag
          docker.io/scruffaluff/bootware:fedora --platform linux/${{
          inputs.platform || 'amd64' }} .
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
